KutuphaneSistemi/Controllers/KitapController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography.Pkcs;
using System.Web;
using System.Web.Mvc;
using KutuphaneSistemi.Models.Entitiy;

namespace KutuphaneSistemi.Controllers
{
    public class KitapController : Controller
    {
        // GET: Kitap
        Db_KutuphaneEntities db = new Db_KutuphaneEntities();
        public ActionResult Index()
        {
            var kitap = db.Tbl_Kitap.ToList();
            return View(kitap);
        }
        public ActionResult Aktif(int id)
        {
            var bul = db.Tbl_Kitap.Find(id);
            bul.Durum = true;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult Pasif(int id)
        {
            var bul = db.Tbl_Kitap.Find(id);
            bul.Durum = false;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult Detay(int id)
        {
            var bul = db.Tbl_Kitap.Find(id);
            return View("Detay", bul);
        }
        [HttpGet]
        public ActionResult Ekle()
        {
            List<SelectListItem> kat = (from x in db.Tbl_Kategori.Where(x=>x.Durum == true).ToList()
                                        select new SelectListItem
                                        {
                                            Value = x.Id.ToString(),
                                            Text = x.KategoriAd
                                        }).ToList();

            ViewBag.kat = kat;
            List<SelectListItem> yazar = (from x in db.Tbl_Yazar.Where(x => x.Durum == true).ToList()
                                          select new SelectListItem
                                          {
                                              Value = x.Id.ToString(),
                                              Text = x.Yazarad + " " + x.Soyad
                                          }).ToList();
            ViewBag.yaz = yazar;
            return View();
        }
        [HttpPost]
        public ActionResult Ekle(Tbl_Kitap p)
        {
            var ktg = db.Tbl_Kategori.Where(x => x.Id == p.Tbl_Kategori.Id).FirstOrDefault();
            var yazar = db.Tbl_Yazar.Where(x => x.Id == p.Tbl_Yazar.Id).FirstOrDefault();
            p.Tbl_Kategori = ktg;
            p.Tbl_Yazar = yazar;
            p.Durum = true;
            db.Tbl_Kitap.Add(p);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult Guncelle(int id)
        {
            var bul = db.Tbl_Kitap.Find(id);
            List<SelectListItem> kat = (from x in db.Tbl_Kategori.ToList()
                                        select new SelectListItem
                                        {
                                            Value = x.Id.ToString(),
                                            Text = x.KategoriAd
                                        }).ToList();
            ViewBag.kat = kat;
            List<SelectListItem> yaz = (from x in db.Tbl_Yazar.ToList()
                                        select new SelectListItem
                                        {
                                            Value = x.Id.ToString(),
                                            Text = x.Yazarad + " " + x.Soyad
                                        }).ToList();
            ViewBag.yaz = yaz;
            return View("Guncelle", bul);
        }
        [HttpPost]
        public ActionResult Guncelle(Tbl_Kitap p)
        {
            var kat = db.Tbl_Kategori.Where(x => x.Id == p.Tbl_Kategori.Id).FirstOrDefault();
            var yaz = db.Tbl_Yazar.Where(x => x.Id == p.Tbl_Yazar.Id).FirstOrDefault();
            var deger = db.Tbl_Kitap.Find(p.Id);
            deger.Sayfasayisi = p.Sayfasayisi;
            deger.Durum = true;
            deger.Kitapad = p.Kitapad;
            deger.Basyımyılı = p.Basyımyılı;
            deger.Yayinevi = p.Yayinevi;
            deger.Katid = kat.Id;
            deger.Yazarid = yaz.Id;
            deger.Foto = p.Foto;
            deger.Detay = p.Detay;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        
    }
}

KutuphaneSistemi/Controllers/UyeKitapController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using KutuphaneSistemi.Models.Entitiy;
namespace KutuphaneSistemi.Controllers
{
    public class UyeKitapController : Controller
    {
        // GET: UyeKitap
        Db_KutuphaneEntities db = new Db_KutuphaneEntities();
        [Authorize]
        public ActionResult Index()
        {
            var kullanici = Session["Kullaniciadi"].ToString();
            var geçmişkitaplar = db.Tbl_Hareket.Where(x => x.Tbl_Uye.Kullaniciadi == kullanici && x.Durum == true).ToList();
            return View(geçmişkitaplar);
        }
        public ActionResult KitapIndex()
        {
            var kullanici = Session["Kullaniciadi"].ToString();
            var kitaplarım = db.Tbl_Hareket.OrderByDescending(x=>x.Id).Where(x => x.Tbl_Uye.Kullaniciadi == kullanici && x.Durum == false).ToList();
            return View(kitaplarım);
        }
        public PartialViewResult Kitap()
        {
            List<SelectListItem> kitap = (from x in db.Tbl_Kitap.Where(x => x.Durum == true).ToList()
                                          select new SelectListItem
                                          {
                                              Value = x.Id.ToString(),
                                              Text = x.Kitapad
                                          }).ToList();
            ViewBag.kitap = kitap;
            return PartialView();
        }
        public PartialViewResult Per()
        {
            List<SelectListItem> per = (from x in db.Tbl_Personel.Where(x => x.Durum == true).ToList()
                                        select new SelectListItem
                                        {
                                            Value = x.Id.ToString(),
                                            Text = x.Personelad + " " + x.Personelsoyad
                                        }).ToList();
            ViewBag.per = per;
            return PartialView();
        }
        [HttpGet]
        public ActionResult KitapAl()
        {
           
            return View();
        }
        [HttpPost]
        public ActionResult KitapAl(Tbl_Hareket p)
        {
            
            p.Durum = false;
            var kitap = db.Tbl_Kitap.Where(x => x.Id == p.Tbl_Kitap.Id).FirstOrDefault();
            var per = db.Tbl_Personel.Where(x => x.Id == p.Tbl_Personel.Id).FirstOrDefault();
            if (kitap != null)
            {
                // Kitap örneğini p.Tbl_Kitap'e atayın
                p.Tbl_Kitap = kitap;
                p.Tbl_Kitap.Durum = false;
                p.Tbl_Personel = per;
                db.Tbl_Hareket.Add(p);
                db.SaveChanges();
            }
            return View();
        }
        public ActionResult Detay(Tbl_Kitap p)
        {
            var bul = db.Tbl_Kitap.FirstOrDefault(x => x.Id == p.Id);
            return View("Detay", bul);
            
        }
        [HttpGet]
        public ActionResult Iade(int id)
        {
            var bul = db.Tbl_Hareket.Find(id);
            return View("Iade", bul);
        }
        
        [HttpPost]
        public ActionResult Iade(Tbl_Hareket p)
        {
            var deger = db.Tbl_Hareket.Find(p.Id);
            deger.Durum = true;
            deger.Tbl_Kitap.Durum = true;
            deger.Teslimtarih = p.Teslimtarih;
            DateTime d1 = Convert.ToDateTime(deger.Alistarihi);
            DateTime d2 = Convert.ToDateTime(DateTime.Now.ToShortDateString());
            TimeSpan fark = d2 - d1;
            if(fark.TotalDays> 0)
            {
                Tbl_Ceza t = new Tbl_Ceza();
                t.uyeid = deger.Uyeid;
                t.Hareketid = deger.Id;
                t.Baslangic = deger.Alistarihi;
                t.Bitis = deger.Teslimtarih;
                t.Paracezası = Convert.ToDecimal(15 * fark.TotalDays);
                db.Tbl_Ceza.Add(t);
            }
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

KutuphaneSistemi/Views/UyeKitap/Detay.cshtml
@model KutuphaneSistemi.Models.Entitiy.Tbl_Kitap
@{
    ViewBag.Title = "Detay";
    Layout = "~/Views/Shared/_UyeLayout.cshtml";
}
<div style="margin-top:20px;">
    <h3 style="color:slateblue"><i>Kitap Detay Sayfası</i></h3>
</div>
<form class="form-group">
    <table class="table table-striped">
        <tr>
            <td><label style="font-weight:bolder">Kitap Adı:</label></td>
            <td>
                @Html.TextBoxFor(x => x.Kitapad, new { @class = "form-control", @readonly = "readonly" })
            </td>
        </tr>
        <tr>
            <td><label style="font-weight:bolder">Yazar Adı:</label></td>
            <td>
                @Html.TextBoxFor(x => x.Tbl_Yazar.Yazarad, new { @class = "form-control", @readonly = "readonly" })
            </td>
        </tr>
        <tr>
            <td><label style="font-weight:bolder">Yazar Soyadı:</label></td>
            <td>
                @Html.TextBoxFor(x => x.Tbl_Yazar.Soyad, new { @class = "form-control", @readonly = "readonly" })
            </td>
        </tr>
        <tr>
            <td><label style="font-weight:bolder">Kategori Adı:</label></td>
            <td>
                @Html.TextBoxFor(x => x.Tbl_Kategori.KategoriAd, new { @class = "form-control", @readonly = "readonly" })
            </td>
        </tr>
        <tr>
            <td><label style="font-weight:bolder">Yayınevi:</label></td>
            <td>
                @Html.TextBoxFor(x => x.Yayinevi, new { @class = "form-control", @readonly = "readonly" })
            </td>
        </tr>
        <tr>
            <td><label style="font-weight:bolder">Basım Yılı:</label></td>
            <td>

                @Html.TextBoxFor(x => x.Basyımyılı, new { @class = "form-control", @readonly = "readonly" })
            </td>
        </tr>
        <tr>
            <td><label style="font-weight:bolder">Sayfa Sayısı:</label></td>
            <td>

                @Html.TextBoxFor(x => x.Sayfasayisi, new { @class = "form-control", @readonly = "readonly" })
            </td>
        </tr>
        <tr>
            <td><label style="font-weight:bolder">Kitap Detay:</label></td>
            <td>
                @Html.TextAreaFor(x => x.Detay, new { @class = "form-control", @readonly = "readonly",@style="height:150px" })
            </td>
        </tr>
    </table>
</form>

KutuphaneSistemi/Views/UyeKitap/Iade.cshtml
@model KutuphaneSistemi.Models.Entitiy.Tbl_Hareket
@{
    ViewBag.Title = "Iade";
    Layout = "~/Views/Shared/_UyeLayout.cshtml";
}

<div style="margin-top:20px;">
    <h3 style="color:slateblue;"><i>Üye Kitap İade Sayfası</i></h3>
</div>
@using (Html.BeginForm("Iade", "UyeKitap", FormMethod.Post))
 {
    <table class="table table-striped">
        <tr>
            <td>Kitap Ad:</td>
            <td>@Html.TextBoxFor(x => x.Tbl_Kitap.Kitapad, new { @class = "form-control", @readonly = "readonly" })</td>
        </tr>
        <tr>
            <td>Personel Ad:</td>
            <td>@Html.TextBoxFor(x => x.Tbl_Personel.Personelad, new { @class = "form-control", @readonly = "readonly" })</td>
        </tr>
        <tr>
            <td>Alış Tarihi:</td>
            <td>@Html.TextBoxFor(x => x.Alistarihi, new { @class = "form-control", @readonly = "readonly" })</td>
        </tr>
        <tr>
            <td>İade Edilmesi Gerken Tarih:</td>
            <td>@Html.TextBoxFor(x => x.İadetarih, new { @class = "form-control", @readonly = "readonly" })</td>
        </tr>
        <tr>
            <td>İade Edilen Tarih:</td>
            <td>
                <input type="text" name="Teslimtarih" value="@DateTime.Now.ToShortDateString()" class="form-control" />
            </td>
        </tr>
        <tr>
            <td></td>
            <td>
                <button class="btn btn-group" style="background-color:purple; color:white;">
                    Kitap İade
                </button>
            </td>
        </tr>
    </table>
 }

KutuphaneSistemi/Views/UyeKitap/Index.cshtml
@using KutuphaneSistemi.Models.Entitiy
@model List<Tbl_Hareket>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_UyeLayout.cshtml";
}

<div style="margin:20px 0px;">
    <h4 style="color:slateblue;"><i>Geçmiş Kitaplarım</i></h4>
</div>
<table class="table table-hover">
    <tr style="background-color:rgb(272,178,22)">
        <th>Kitap Adı</th>
        <th>Alış Tarihi</th>
        <th>Teslim Tarihi</th>
        <th>Detay</th>
    </tr>
    <tbody>
        @foreach(var x in Model)
            {
                <tr>
                    <td>@x.Tbl_Kitap.Kitapad</td>
                    <td>@Convert.ToDateTime(x.Alistarihi).ToShortDateString()</td>
                    <td>@Convert.ToDateTime(x.Teslimtarih).ToShortDateString()</td>
                    <td>
                        <a href="/UyeKitap/Detay/@x.Tbl_Kitap.Id" class="btn btn-success">Kitap Detay</a>
                    </td>
                </tr>
            }
    </tbody>
</table>

KutuphaneSistemi/Views/UyeKitap/Kitap.cshtml
@model KutuphaneSistemi.Models.Entitiy.Tbl_Hareket
<tr>
    <td>Kitap Ad:</td>
    <td>
        @Html.DropDownListFor(x => x.Tbl_Kitap.Id, (List<SelectListItem>)ViewBag.kitap, "Lütfen Kitap Seçiniz", new { @class = "form-control", @required = "required" })
    </td>
</tr>

KutuphaneSistemi/Views/UyeKitap/KitapAl.cshtml
@model KutuphaneSistemi.Models.Entitiy.Tbl_Hareket
@{
    ViewBag.Title = "KitapAl";
    Layout = "~/Views/Shared/_UyeLayout.cshtml";
}

<div style="margin:20px 0px;">
    <h4 style="color:slateblue"><i>Ödünç Kitap Alma</i></h4>
</div>
<form method="post">
    <table class="table table-striped">
        <tr>
            <td>Üye Ad:</td>
            <td> 
                <input type="text" name="Uyeid" value="@Session["Id"].ToString()" readonly="readonly" class="form-control"/>
            </td>
        </tr>
        @Html.Action("Kitap")
        @Html.Action("Per")
        <tr>
            <td>Alış Tarihi:</td>
            <td>
                <input type="text" name="Alistarihi" value="@DateTime.Now.ToShortDateString()" readonly="readonly" class="form-control"/>
            </td>
        </tr>
        <tr>
            <td>İade Tarihi:</td>
            <td>
                <input type="text" name="İadetarih" value="@DateTime.Now.AddDays(1).ToShortDateString()" readonly="readonly" class="form-control" />
            </td>
        </tr>
        <tr>
            <td></td>
            <td>
                <button class="btn btn-success">Ödünç Kitap Al</button>
            </td>
        </tr>
    </table>
</form>

KutuphaneSistemi/Views/UyeKitap/KitapIndex.cshtml
@using KutuphaneSistemi.Models.Entitiy
@model List<Tbl_Hareket>
@{
    ViewBag.Title = "KitapIndex";
    Layout = "~/Views/Shared/_UyeLayout.cshtml";
}

<div style="margin:20px 0px;">
    <h4 style="color:slateblue"><i>Kitaplarım</i></h4>
</div>
<table class="table table-striped">
    <tr style="background-color:rgb(252,178,22)">
        <th>Kitap Ad</th>
        <th>Alış Tarihi</th>
        <th>İade Tarihi</th>
        <th>Detay</th>
        <th>İade Et</th>
    </tr>
    <tbody>
        @foreach(var x in Model)
            {
                <tr>
                    <td>@x.Tbl_Kitap.Kitapad</td>
                    <td>@Convert.ToDateTime(x.Alistarihi).ToShortDateString()</td>
                    <td>@Convert.ToDateTime(x.İadetarih).ToShortDateString()</td>
                    <td>
                        <a href="/UyeKitap/Detay/@x.Tbl_Kitap.Id" class="btn btn-success">Kitap Detay</a>
                    </td>
                    <td>
                        <a href="/UyeKitap/Iade/@x.Id" class="btn btn-group" style="background-color:purple; color:white;">Kitap İade Et</a>
                    </td>
                </tr>
            }
    </tbody>
</table>

KutuphaneSistemi/Views/UyeKitap/Per.cshtml
@model KutuphaneSistemi.Models.Entitiy.Tbl_Hareket
<tr>
    <td>Kitap Ad:</td>
    <td>
        @Html.DropDownListFor(x => x.Tbl_Personel.Id, (List<SelectListItem>)ViewBag.per, "Lütfen Personel Seçiniz", new { @class = "form-control", @required = "required" })
    </td>
</tr>