KutuphaneSistemi/Controllers/OduncKitapAlController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using KutuphaneSistemi.Models.Entitiy;
namespace KutuphaneSistemi.Controllers
{
    public class OduncKitapAlController : Controller
    {
        // GET: OduncKitapAl
        Db_KutuphaneEntities db = new Db_KutuphaneEntities();
        public ActionResult Index()
        {
            var odunckitap = db.Tbl_Hareket.OrderByDescending(x=>x.Id).Where(x=>x.Durum== false).ToList();
            return View(odunckitap);
        }
        [HttpGet]
        public ActionResult Teslimet(int id)
        {
            var bul = db.Tbl_Hareket.Find(id);
            return View("Teslimet", bul);
        }
        [HttpPost]
        public ActionResult Guncelle(Tbl_Hareket p)
        {
            
            var deger = db.Tbl_Hareket.Find(p.Id);
            deger.Durum = true;
            deger.Tbl_Kitap.Durum = true;
            deger.Teslimtarih = p.Teslimtarih;
            DateTime dt1 = DateTime.Parse(deger.İadetarih.ToString());
            DateTime dt2 = Convert.ToDateTime(DateTime.Now.ToShortDateString());
            TimeSpan day = dt2 - dt1;
            if(day.TotalDays > 0)
            {
                Tbl_Ceza t = new Tbl_Ceza();
                t.uyeid = deger.Uyeid;
                t.Hareketid = p.Id;
                t.Baslangic = p.Alistarihi;
                t.Bitis = p.Teslimtarih;
                t.Paracezası = Convert.ToDecimal(15 * (day.TotalDays));
                db.Tbl_Ceza.Add(t);
            }
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

KutuphaneSistemi/Views/OduncKitapAl/Index.cshtml
@using KutuphaneSistemi.Models.Entitiy
@model List<Tbl_Hareket>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<div style="margin:20px 0px;">
    <h3>Kitap İade Sayfası</h3>
</div>
<table class="table table-bordered">
    <tr>
        <th>Id</th>
        <th>Üye</th>
        <th>Kitap</th>
        <th>Personel</th>
        <th>Alış Tarihi</th>
        <th>İade Tarihi</th>
        <th>Durum</th>
        <th>İade İşlemi</th>
    </tr>
    <tbody>
        @{ string durum = "";}
        @foreach(var x in Model)
        {
            if(x.Durum== false)
            {
                durum = "Teslim Alınmadı";
            }
            if(x.Durum == true)
            {
                durum = "Teslim Alındı";
            }
                <tr>
                    <td>@x.Id</td>
                    <td>@x.Tbl_Uye.Ad @x.Tbl_Uye.Soyad</td>
                    <td>@x.Tbl_Kitap.Kitapad</td>
                    <td>@x.Tbl_Personel.Personelad @x.Tbl_Personel.Personelsoyad</td>
                    <td>@Convert.ToDateTime(x.Alistarihi).ToString("dd/MM/yyyy")</td>
                    <td>@Convert.ToDateTime(x.İadetarih).ToString("dd/MM/yyyy")</td>
                    <td>@durum</td>
                    <td>
                        <a href="/OduncKitapAl/Teslimet/@x.Id" class="btn btn-group" style="background-color:aqua">Kitap İade Et</a>
                    </td>
                </tr>
            }
    </tbody>
</table>

KutuphaneSistemi/Views/OduncKitapAl/Teslimet.cshtml
@model KutuphaneSistemi.Models.Entitiy.Tbl_Hareket
@{
    ViewBag.Title = "Teslimet";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<div style="margin-top:20px">
    <h3>Kitap Teslim Alma Sayfası</h3>
</div>
@using (Html.BeginForm("Guncelle", "OduncKitapAl", FormMethod.Post))
{
    <div style="margin-top:20px;">
        <label>Hareket Id:</label>
        @Html.TextBoxFor(x => x.Id, new { @class = "form-control", @readonly = "readonly" })
    </div>
    <div style="margin-top:20px;">
        <label>Üye Ad:</label>
        @Html.TextBoxFor(x => x.Tbl_Uye.Ad, new { @class = "form-control", @readonly = "readonly" })
    </div>
    <div style="margin-top:20px;">
        <label>Kitap Ad:</label>
        @Html.TextBoxFor(x => x.Tbl_Kitap.Kitapad, new { @class = "form-control", @readonly = "readonly" })
    </div>
    <div style="margin-top:20px;">
        <label>Personel Ad:</label>
        @Html.TextBoxFor(x => x.Tbl_Personel.Personelad, new { @class = "form-control", @readonly = "readonly" })
    </div>
    <div style="margin-top:20px;">
        <label>Alış Tarihi:</label>
        @Html.TextBoxFor(x => x.Alistarihi, new { @class = "form-control", @readonly = "readonly" })
    </div>
    <div style="margin-top:20px;">
        <label>İade Edilmesi Gereken Tarih:</label>
        @Html.TextBoxFor(x => x.İadetarih,  new { @class = "form-control", @readonly = "readonly" })
    </div>
    <div style="margin-top:20px;">
        <label>İade Edilen Tarih</label>
        <input type="text" name="Teslimtarih" value="@DateTime.Now.ToShortDateString()" class="form-control"/>
    </div>
    
    <div style="margin-top:20px;">
        <button class="btn btn-group" style="background-color:aqua;">Ödünç Kitap Teslim Al</button>
    </div>
}