KutuphaneSistemi/Controllers/HakkımızdaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using KutuphaneSistemi.Models.Entitiy;
namespace KutuphaneSistemi.Controllers
{
    public class HakkımızdaController : Controller
    {
        // GET: Hakkımızda
        Db_KutuphaneEntities db = new Db_KutuphaneEntities();
        [HttpGet]
        public ActionResult Index()
        {
            var hakkımızda = db.Tbl_Hakkımızda.ToList();
            return View(hakkımızda);
        }
        [HttpPost]
        public ActionResult Index(Tbl_Hakkımızda p)
        {
            var deger = db.Tbl_Hakkımızda.Find(1);
            deger.icerik1 = p.icerik1;
            deger.icerik2 = p.icerik2;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

KutuphaneSistemi/Controllers/UyePanelController.cs
using KutuphaneSistemi.Models.Entitiy;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace KutuphaneSistemi.Controllers
{
    public class UyePanelController : Controller
    {
        Db_KutuphaneEntities db = new Db_KutuphaneEntities();
        // GET: UyePanel
        [HttpGet]
        [Authorize]
        
        public ActionResult Index()
        {
            var kullanıcı = (string)Session["Kullaniciadi"];
            var deger = db.Tbl_Uye.FirstOrDefault(x => x.Kullaniciadi == kullanıcı);
            return View(deger);
        }
        [HttpPost]
        public ActionResult Index(Tbl_Uye p)
        {
            var kullanıcı = (string)Session["Kullaniciadi"];
            var uye = db.Tbl_Uye.FirstOrDefault(x => x.Kullaniciadi == kullanıcı);
            uye.Sifre = p.Sifre;
            uye.Telefon = p.Telefon;
            uye.Mail = p.Mail;
            uye.Okul = p.Okul;
            uye.Yas = p.Yas;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult Hesap()
        {
            var kullaniciadi = Session["kullaniciadi"].ToString();
            var deger = db.Tbl_Uye.FirstOrDefault(x => x.Kullaniciadi == kullaniciadi);
            return View(deger);
        }
        public ActionResult Hakkımızda()
        {
            var hakkımızda = db.Tbl_Hakkımızda.ToList();
            return View(hakkımızda);
        }
        public ActionResult Yardım()
        {
            return View();
        }
    }
}

KutuphaneSistemi/Views/UyePanel/Hakkımızda.cshtml
@using KutuphaneSistemi.Models.Entitiy
@model List<Tbl_Hakkımızda>
@{
    ViewBag.Title = "Hakkımızda";
    Layout = "~/Views/Shared/_UyeLayout.cshtml";
}

<div style="margin:20px 0px;">
    <h3 style="color:cadetblue"><i>Hakkımızda</i></h3>
</div>

<div >
       @foreach(var x in Model)
            {
                <p>@x.icerik1</p>
                <br />
                <p>@x.icerik2</p>
            }
</div>

KutuphaneSistemi/Views/UyePanel/Hesap.cshtml
@{
    ViewBag.Title = "Hesap";
    Layout = "~/Views/Shared/_UyeLayout.cshtml";
}

<div style="margin-top:20px;">
    <h3 style="color:cadetblue;"><i>Hesap Bilgileri</i></h3>
</div>
<form >
    <table class="table table-hover">
        <tr>
            <td><label> Ad:</label></td>
            <td>
                @Session["Ad"].ToString()
            </td>
        </tr>
        <tr>
            <td><label> Soyad:</label></td>
            <td>
                @Session["Soyad"].ToString()
            </td>
        </tr>
        <tr>
            <td><label>Yas:</label></td>
            <td>
                @Session["Yas"].ToString()
            </td>
        </tr>

        <tr>
            <td><label> Okul:</label></td>
            <td>
                @Session["Okul"].ToString()
            </td>
        </tr>
        <tr>
            <td><label> Mail:</label></td>
            <td>
                @Session["Mail"].ToString()
            </td>
        </tr>
        <tr>
            <td><label> Telefon:</label></td>
            <td>
                @Session["Telefon"].ToString()
            </td>
        </tr>
        <tr>
            <td><label>Kullanıcı Adı:</label></td>
            <td>
                @Session["Kullaniciadi"].ToString()
            </td>
        </tr>
    </table>
</form>

KutuphaneSistemi/Views/UyePanel/Index.cshtml
@model KutuphaneSistemi.Models.Entitiy.Tbl_Uye
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_UyeLayout.cshtml";
}

<div style="margin:20px 0px;">
    <h4 style="color: lightseagreen"><i>Üye Profil</i></h4>
</div>
@using (Html.BeginForm("Index", "UyePanel", FormMethod.Post)) { 
    <table class="table table-hover">
        <tr>
            <td><label style="font-weight:bolder;">Id:</label></td>
            <td>

                @Session["Id"].ToString()

            </td>
        </tr>
        <tr>
            <td><label style="font-weight:bolder;">Ad:</label></td>
            <td>

                @Session["Ad"].ToString()
            </td>
        </tr>
        <tr>
            <td>
                <label style="font-weight:bolder;">Soyad:</label>
            </td>
            <td>


                @Session["Soyad"].ToString()
            </td>
        </tr>
        <tr>
            <td>
                <label style="font-weight:bolder;">Kullanıcı Adı:</label>
            </td>
            <td>

                @HttpContext.Current.User.Identity.Name
            </td>
        </tr>
        <tr>
            <td>
                <label style="font-weight:bolder;">Mail:</label>
            </td>
            <td>
                @Html.TextBoxFor(x => x.Mail, new { @class = "form-control" })

            </td>
        </tr>
        <tr>
            <td>
                <label style="font-weight:bolder;">Telefon:</label>
            </td>
            <td>

                @Html.TextBoxFor(x => x.Telefon, new { @class = "form-control" })
            </td>
        </tr>
        <tr>
            <td>
                <label style="font-weight:bolder;">Okul:</label>
            </td>
            <td>

                @Html.TextBoxFor(x => x.Okul, new { @class = "form-control" })
            </td>
        </tr>
        <tr>
            <td>
                <label style="font-weight:bolder;">Yaş:</label>
            </td>
            <td>

                @Html.TextBoxFor(x => x.Yas, new { @class = "form-control" })
            </td>
        </tr>

        <tr>
            <td>
                <label style="font-weight:bolder;">Şifre:</label>
            </td>
            <td>
                @Html.TextBoxFor(x => x.Sifre, new { @class = "form-control" })
            </td>
        </tr>
        <tr>
            <td>
                <button class="btn btn-warning">Şifre Güncelle</button>
            </td>
        </tr>
    </table>
}

KutuphaneSistemi/Views/UyePanel/Yardım.cshtml
@{
    ViewBag.Title = "Yardım";
    Layout = "~/Views/Shared/_UyeLayout.cshtml";
}
<h2 style="color:cadetblue"><i>Kütüphane Sistemi Yardım Merkezi</i></h2>

<h4>Sık Sorulan Sorular (FAQs):</h4>
<ol>
    <li>
        <p style="font-weight:bold;">Nasıl Üye Olurum?</p>
        <p>Üye olmak için ana sayfanın sağ üst köşesinde bulunan "Üye Ol" veya "Kayıt Ol" butonuna tıklayın ve gerekli bilgileri doldurun.</p>
    </li>
    <li>
        <p style="font-weight:bold;">Şifremi Unuttum, Ne Yapmalıyım?</p>
        <p>
            Şifrenizi sıfırlamak için "Şifremi Unuttum" seçeneğine tıklayın ve e-posta adresinizi girin. Size şifre sıfırlama talimatları gönderilecektir.
        </p>
    </li>
    <li>
        <p style="font-weight:bold;">Kitap İade ve İade Koşulları Nelerdir?</p>
        <p>Kitap iade politikamız hakkında daha fazla bilgi için site adminine mesaj atınız.</p>
    </li> 
</ol>

<ul>
    <li>
        <p style="font-weight:bold">Kılavuzlar ve Talimatlar:</p>
        <p>[Nasıl Kitap Teslim Alınır?] kılavuzu için tıklayın.</p>
        <p> Profilim sayfasından hesap ayarlarını değiştirebilirsiniz.</p>
    </li>
    <li>
        <p style="font-weight:bold">Güncellemeler ve Duyurular:</p>
        <p>Web sitemizle ilgili güncellemeler ve duyurular için Duyurular sayfasını ziyaret edin.</p>
    </li>
    <li>
        <p style="font-weight:bold">Sorun Giderme Rehberleri:</p>
        <p>Sık karşılaşılan sorunları çözmek için Yardım sayfasına göz atın.</p>
    </li>
</ul>

<div style="margin:20px 20px;">
    <h4>İletişim Bilgileri:</h4>
    <h6>Müşteri Desteği E-Posta:</h6> <p>destek@example.com</p>
    <h6>Telefon Desteği:</h6> <p>+123-456-7890</p>
</div>



 