KutuphaneSistemi/Controllers/KitapController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography.Pkcs;
using System.Web;
using System.Web.Mvc;
using KutuphaneSistemi.Models.Entitiy;

namespace KutuphaneSistemi.Controllers
{
    public class KitapController : Controller
    {
        // GET: Kitap
        Db_KutuphaneEntities db = new Db_KutuphaneEntities();
        public ActionResult Index()
        {
            var kitap = db.Tbl_Kitap.ToList();
            return View(kitap);
        }
        public ActionResult Aktif(int id)
        {
            var bul = db.Tbl_Kitap.Find(id);
            bul.Durum = true;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult Pasif(int id)
        {
            var bul = db.Tbl_Kitap.Find(id);
            bul.Durum = false;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult Detay(int id)
        {
            var bul = db.Tbl_Kitap.Find(id);
            return View("Detay", bul);
        }
        [HttpGet]
        public ActionResult Ekle()
        {
            List<SelectListItem> kat = (from x in db.Tbl_Kategori.Where(x=>x.Durum == true).ToList()
                                        select new SelectListItem
                                        {
                                            Value = x.Id.ToString(),
                                            Text = x.KategoriAd
                                        }).ToList();

            ViewBag.kat = kat;
            List<SelectListItem> yazar = (from x in db.Tbl_Yazar.Where(x => x.Durum == true).ToList()
                                          select new SelectListItem
                                          {
                                              Value = x.Id.ToString(),
                                              Text = x.Yazarad + " " + x.Soyad
                                          }).ToList();
            ViewBag.yaz = yazar;
            return View();
        }
        [HttpPost]
        public ActionResult Ekle(Tbl_Kitap p)
        {
            var ktg = db.Tbl_Kategori.Where(x => x.Id == p.Tbl_Kategori.Id).FirstOrDefault();
            var yazar = db.Tbl_Yazar.Where(x => x.Id == p.Tbl_Yazar.Id).FirstOrDefault();
            p.Tbl_Kategori = ktg;
            p.Tbl_Yazar = yazar;
            p.Durum = true;
            db.Tbl_Kitap.Add(p);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult Guncelle(int id)
        {
            var bul = db.Tbl_Kitap.Find(id);
            List<SelectListItem> kat = (from x in db.Tbl_Kategori.ToList()
                                        select new SelectListItem
                                        {
                                            Value = x.Id.ToString(),
                                            Text = x.KategoriAd
                                        }).ToList();
            ViewBag.kat = kat;
            List<SelectListItem> yaz = (from x in db.Tbl_Yazar.ToList()
                                        select new SelectListItem
                                        {
                                            Value = x.Id.ToString(),
                                            Text = x.Yazarad + " " + x.Soyad
                                        }).ToList();
            ViewBag.yaz = yaz;
            return View("Guncelle", bul);
        }
        [HttpPost]
        public ActionResult Guncelle(Tbl_Kitap p)
        {
            var kat = db.Tbl_Kategori.Where(x => x.Id == p.Tbl_Kategori.Id).FirstOrDefault();
            var yaz = db.Tbl_Yazar.Where(x => x.Id == p.Tbl_Yazar.Id).FirstOrDefault();
            var deger = db.Tbl_Kitap.Find(p.Id);
            deger.Sayfasayisi = p.Sayfasayisi;
            deger.Durum = true;
            deger.Kitapad = p.Kitapad;
            deger.Basyımyılı = p.Basyımyılı;
            deger.Yayinevi = p.Yayinevi;
            deger.Katid = kat.Id;
            deger.Yazarid = yaz.Id;
            deger.Foto = p.Foto;
            deger.Detay = p.Detay;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        
    }
}

KutuphaneSistemi/Views/Kitap/Detay.cshtml
@model KutuphaneSistemi.Models.Entitiy.Tbl_Kitap
@{
    ViewBag.Title = "Detay";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<div style="margin-top:20px;">
    <h3>Kitap Detay Sayfası</h3>
</div>
<form class="form-group">
    <div style="margin-top:20px;">
        <label>Kitap Adı:</label>
        @Html.TextBoxFor(x => x.Kitapad, new { @class = "form-control", @readonly = "readonly" })
    </div>
    <div style="margin-top:20px;">
        <label>Kategori:</label>
        @Html.TextBoxFor(x => x.Tbl_Kategori.KategoriAd, new { @class = "form-control", @readonly = "readonly" })
    </div>
    <div style="margin-top:20px;">
        <label>Yazar Ad:</label>
        @Html.TextBoxFor(x => x.Tbl_Yazar.Yazarad, new { @class = "form-control", @readonly = "readonly" })
    </div>
    <div style="margin-top:20px;">
        <label>Yazar Soyad:</label>
        @Html.TextBoxFor(x => x.Tbl_Yazar.Soyad, new { @class = "form-control", @readonly = "readonly" })
    </div>
    <div style="margin-top:20px;">
        <label>Sayfa Sayısı:</label>
        @Html.TextBoxFor(x => x.Sayfasayisi, new { @class = "form-control", @readonly = "readonly" })
    </div>
    <div style="margin-top:20px;">
        <label>Yayın Evi:</label>
        @Html.TextBoxFor(x => x.Yayinevi, new { @class = "form-control", @readonly = "readonly" })
    </div>
    <div style="margin-top:20px;">
        <label>Basım Yılı:</label>
        @Html.TextBoxFor(x => x.Basyımyılı, new { @class = "form-control", @readonly = "readonly" })
    </div>
    <div style="margin-top:20px;">
        <label>Durum:</label>
        @Html.TextBoxFor(x => x.Durum, new { @class = "form-control", @readonly = "readonly" })
    </div>
    <div style="margin-top:20px;">
        <label>Kitap Fotoğraf:</label>
        @Html.TextBoxFor(x => x.Foto, new { @class = "form-control", @readonly = "readonly" })
    </div>
    <div style="margin-top:20px;">
        <label>Kitap Detay:</label>
        @Html.TextAreaFor(x => x.Detay, new { @class = "form-control", @readonly = "readonly" , @style="height:200px;"})
    </div>
</form>

KutuphaneSistemi/Views/Kitap/Ekle.cshtml
@model KutuphaneSistemi.Models.Entitiy.Tbl_Kitap
@{
    ViewBag.Title = "Ekle";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<div style="margin-top:20px;">
    <h3>Kitap Ekleme Sayfası</h3>
</div>
<form method="post" class="form-group">
    <div style="margin-top:20px;">
        <label>Kitap Adı:</label>
        @Html.TextBoxFor(x => x.Kitapad, new { @class = "form-control", @required = "required" })

    </div>
    <div style="margin-top:20px;">
        <label>Kategori:</label>
        @Html.DropDownListFor(x => x.Tbl_Kategori.Id, (List<SelectListItem>)ViewBag.kat,"Lütfen Kategori Seçiniz" ,new { @class = "form-control", @required = "required" })
    </div>
    <div style="margin-top:20px;">
        <label>Yazar:</label>
        @Html.DropDownListFor(x => x.Tbl_Yazar.Id, (List<SelectListItem>)ViewBag.yaz,"Lütfen Yazar Seçiniz" ,new { @class = "form-control", @required = "required" })
    </div>
    <div style="margin-top:20px;">
        <label>Yayınevi:</label>
        @Html.TextBoxFor(x => x.Yayinevi, new { @class = "form-control", @required = "required" })
    </div>
    <div style="margin-top:20px;">
        <label>Basımyılı:</label>
        @Html.TextBoxFor(x => x.Basyımyılı, new { @class = "form-control", @required = "required" })

    </div>
    <div style="margin-top:20px;">
        <label>Sayfa Sayısı:</label>
        @Html.TextBoxFor(x => x.Sayfasayisi, new { @class = "form-control", @required = "required" })
    </div>
    <div style="margin-top:20px;">
        <label>Kitap Fotoğraf:</label>
        @Html.TextBoxFor(x => x.Foto, new { @class = "form-control", @required = "required" })
    </div>
    <div style="margin-top:20px;">
        <label>Kitap Detay:</label>
        @Html.TextAreaFor(x => x.Detay, new { @class = "form-control", @required = "required", @style="height:150px;" })
    </div>
    <div style="margin-top:20px;">
        <button class="btn btn-primary">Kitap Ekle</button>
    </div>
</form>

KutuphaneSistemi/Views/Kitap/Guncelle.cshtml
@model KutuphaneSistemi.Models.Entitiy.Tbl_Kitap
@{
    ViewBag.Title = "Guncelle";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<div style="margin-top:20px;">
    <h3>Kitap Güncelleme Sayfası</h3>
</div>
@using (Html.BeginForm("Guncelle", "Kitap", FormMethod.Post))
{
    <div style="margin-top:20px;">
        <label>Kitap Adı:</label>
        @Html.TextBoxFor(x => x.Kitapad, new { @class = "form-control", @required = "required" })
    </div>
    <div style="margin-top:20px;">
        <label>Kategori:</label>
        @Html.DropDownListFor(x => x.Tbl_Kategori.Id, (List<SelectListItem>)ViewBag.kat, new { @class = "form-control", @required = "required" })
    </div>
    <div style="margin-top:20px;">
        <label>Yazar:</label>
        @Html.DropDownListFor(x => x.Tbl_Yazar.Id, (List<SelectListItem>)ViewBag.yaz, new { @class = "form-control", @required = "required" })
    </div>
    <div style="margin-top:20px;">
        <label>Sayfa Sayısı:</label>
        @Html.TextBoxFor(x => x.Sayfasayisi, new { @class = "form-control", @required = "required" })
    </div>
    <div style="margin-top:20px;">
        <label>Yayın evi:</label>
        @Html.TextBoxFor(x => x.Yayinevi, new { @class = "form-control", @required = "required" })
    </div>
    <div style="margin-top:20px;">
        <label>Basımyılı:</label>
        @Html.TextBoxFor(x => x.Basyımyılı, new { @class = "form-control", @required = "required" })
    </div>
    <div style="margin-top:20px;">
        <label>Kitap Fotoğraf:</label>
        @Html.TextBoxFor(x => x.Foto, new { @class = "form-control", @required = "required" })
    </div>
    <div style="margin-top:20px;">
        <label>Kitap Detay:</label>
        @Html.TextAreaFor(x => x.Detay, new { @class = "form-control", @required = "required", @style="height:200px;" })
    </div>
    <div style="margin-top:20px;">
        <button class="btn btn-warning">Kitap Güncelle</button>
    </div>

}

KutuphaneSistemi/Views/Kitap/Index.cshtml
@using KutuphaneSistemi.Models.Entitiy
@model List<Tbl_Kitap>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<div style="margin-top:20px;">
    <h3>Kitap Sayfası</h3>
</div>
<table class="table table-bordered">
    <tr>
        <th>Id</th>
        <th>Kitap Adı</th>
        <th>Kategori </th>
        <th>Yazar Adı</th>
        <th>Durum</th>
        <th>İşlemler</th>
        <th>Güncelle</th>
        <th>Detay</th>
        
    </tr>
    <tbody>

        @{ string durum = "";}
        @foreach(var x in Model)
        {
            if(x.Durum == true)
            {
                durum = "Aktif";
            }
            if(x.Durum == false)
            {
                durum = "Pasif";
            }
                <tr>
                    <td>@x.Id</td>
                    <td>@x.Kitapad</td>
                    <td>@x.Tbl_Kategori.KategoriAd</td>
                    <td>@x.Tbl_Yazar.Yazarad @x.Tbl_Yazar.Soyad</td>
                    <td>@durum</td>
                    <td>
                        @Html.ActionLink("Aktif Yap","Aktif",new { id = x.Id}, new {@class="btn btn-info", onclick="return confirm('Aktif yapmak ister misiniz ?')"})
                        @Html.ActionLink("Pasif Yap","Pasif", new {id = x.Id}, new {@class="btn btn-danger", onclick="return confirm('Pasif yapmak ister misiniz ?')"})
                    </td>
                    <td>
                        <a href="/Kitap/Guncelle/@x.Id" class="btn btn-success">Kitap Güncelle</a>
                    </td>
                    <td>
                        <a href="/Kitap/Detay/@x.Id" class="btn btn-warning">Kitap Detay</a>
                    </td>
                    
                </tr>
            }
    </tbody>
</table>
<div style="margin-top:20px;">
    <a href="/Kitap/Ekle/" class="btn btn-primary">Kitap Ekle</a>
</div>